@startuml Sequenzdiagramm

actor Client

boundary DozentGetController
control DozentReadService
control DozentRepository

Client -> DozentGetController : GET / getById()
DozentGetController -> DozentReadService: findById()
DozentReadService -> DozentRepository: findById()


@enduml
